/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as MasterRouteRouteImport } from './routes/master/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterIndexRouteImport } from './routes/master/index'
import { Route as MasterSubscriptionsRouteImport } from './routes/master/subscriptions'
import { Route as MasterSettingsRouteImport } from './routes/master/settings'
import { Route as MasterDashboardRouteImport } from './routes/master/dashboard'
import { Route as MasterCompaniesRouteImport } from './routes/master/companies'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedFlowsRouteImport } from './routes/_authenticated/flows'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedFlowsFlowIdRouteImport } from './routes/_authenticated/flows.$flowId'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRouteRoute = MasterRouteRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterSubscriptionsRoute = MasterSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterSettingsRoute = MasterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterDashboardRoute = MasterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MasterRouteRoute,
} as any)
const MasterCompaniesRoute = MasterCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => MasterRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlowsRoute = AuthenticatedFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlowsFlowIdRoute =
  AuthenticatedFlowsFlowIdRouteImport.update({
    id: '/$flowId',
    path: '/$flowId',
    getParentRoute: () => AuthenticatedFlowsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/master': typeof MasterRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/set-password': typeof SetPasswordRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/flows': typeof AuthenticatedFlowsRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/master/companies': typeof MasterCompaniesRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/subscriptions': typeof MasterSubscriptionsRoute
  '/master/': typeof MasterIndexRoute
  '/flows/$flowId': typeof AuthenticatedFlowsFlowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/set-password': typeof SetPasswordRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/flows': typeof AuthenticatedFlowsRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/master/companies': typeof MasterCompaniesRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/subscriptions': typeof MasterSubscriptionsRoute
  '/master': typeof MasterIndexRoute
  '/flows/$flowId': typeof AuthenticatedFlowsFlowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/master': typeof MasterRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/flows': typeof AuthenticatedFlowsRouteWithChildren
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/master/companies': typeof MasterCompaniesRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/subscriptions': typeof MasterSubscriptionsRoute
  '/master/': typeof MasterIndexRoute
  '/_authenticated/flows/$flowId': typeof AuthenticatedFlowsFlowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/master'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/set-password'
    | '/connections'
    | '/contacts'
    | '/crm'
    | '/flows'
    | '/inbox'
    | '/schedules'
    | '/settings'
    | '/master/companies'
    | '/master/dashboard'
    | '/master/settings'
    | '/master/subscriptions'
    | '/master/'
    | '/flows/$flowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/set-password'
    | '/connections'
    | '/contacts'
    | '/crm'
    | '/flows'
    | '/inbox'
    | '/schedules'
    | '/settings'
    | '/master/companies'
    | '/master/dashboard'
    | '/master/settings'
    | '/master/subscriptions'
    | '/master'
    | '/flows/$flowId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/master'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/set-password'
    | '/_authenticated/connections'
    | '/_authenticated/contacts'
    | '/_authenticated/crm'
    | '/_authenticated/flows'
    | '/_authenticated/inbox'
    | '/_authenticated/schedules'
    | '/_authenticated/settings'
    | '/master/companies'
    | '/master/dashboard'
    | '/master/settings'
    | '/master/subscriptions'
    | '/master/'
    | '/_authenticated/flows/$flowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MasterRouteRoute: typeof MasterRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/subscriptions': {
      id: '/master/subscriptions'
      path: '/subscriptions'
      fullPath: '/master/subscriptions'
      preLoaderRoute: typeof MasterSubscriptionsRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/settings': {
      id: '/master/settings'
      path: '/settings'
      fullPath: '/master/settings'
      preLoaderRoute: typeof MasterSettingsRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/dashboard': {
      id: '/master/dashboard'
      path: '/dashboard'
      fullPath: '/master/dashboard'
      preLoaderRoute: typeof MasterDashboardRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/master/companies': {
      id: '/master/companies'
      path: '/companies'
      fullPath: '/master/companies'
      preLoaderRoute: typeof MasterCompaniesRouteImport
      parentRoute: typeof MasterRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flows': {
      id: '/_authenticated/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AuthenticatedFlowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flows/$flowId': {
      id: '/_authenticated/flows/$flowId'
      path: '/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof AuthenticatedFlowsFlowIdRouteImport
      parentRoute: typeof AuthenticatedFlowsRoute
    }
  }
}

interface AuthenticatedFlowsRouteChildren {
  AuthenticatedFlowsFlowIdRoute: typeof AuthenticatedFlowsFlowIdRoute
}

const AuthenticatedFlowsRouteChildren: AuthenticatedFlowsRouteChildren = {
  AuthenticatedFlowsFlowIdRoute: AuthenticatedFlowsFlowIdRoute,
}

const AuthenticatedFlowsRouteWithChildren =
  AuthenticatedFlowsRoute._addFileChildren(AuthenticatedFlowsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedFlowsRoute: typeof AuthenticatedFlowsRouteWithChildren
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedFlowsRoute: AuthenticatedFlowsRouteWithChildren,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MasterRouteRouteChildren {
  MasterCompaniesRoute: typeof MasterCompaniesRoute
  MasterDashboardRoute: typeof MasterDashboardRoute
  MasterSettingsRoute: typeof MasterSettingsRoute
  MasterSubscriptionsRoute: typeof MasterSubscriptionsRoute
  MasterIndexRoute: typeof MasterIndexRoute
}

const MasterRouteRouteChildren: MasterRouteRouteChildren = {
  MasterCompaniesRoute: MasterCompaniesRoute,
  MasterDashboardRoute: MasterDashboardRoute,
  MasterSettingsRoute: MasterSettingsRoute,
  MasterSubscriptionsRoute: MasterSubscriptionsRoute,
  MasterIndexRoute: MasterIndexRoute,
}

const MasterRouteRouteWithChildren = MasterRouteRoute._addFileChildren(
  MasterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MasterRouteRoute: MasterRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
