// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnkctnmmxltsbpnqqnwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxua2N0bm1teGx0c2JwbnFxbndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3MjQ5NTUsImV4cCI6MjA5NjMwMDk1NX0.6kekDC9jaD2QcQoUn8HxsmI5kB8vqXLoCu95hpjOkSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});